
services:
  postgres:
    image: postgres:15
    container_name: diploma_postgres
    restart: always
    environment:
      POSTGRES_DB: diploma_db
      POSTGRES_USER: diploma_user
      POSTGRES_PASSWORD: diploma_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
