spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/diploma_db}
    username: ${SPRING_DATASOURCE_USERNAME:diploma_user}
    password: ${SPRING_DATASOURCE_PASSWORD:diploma_pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
